version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
    environment:
      - REDIS_PASSWORD=1234
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    networks:
      - app-network

  currency-exchange-service:
    image: nbaez001/currency-exchange-service:1.0
    restart: always
    ports:
      - "8081:8081"
    networks:
      - app-network

  currency-conversion-service:
    image: nbaez001/currency-conversion-service:1.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=1234
      - SPRING_EXCHANGE_SERVICE_URL=http://currency-exchange-service:8081
    depends_on:
      - redis
      - currency-exchange-service
    networks:
      - app-network

volumes:
  redis-data: