server:
  port: 8080
spring:
  application:
    name: currency-conversion-service
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:1234}
resilience4j:
  circuitbreaker:
    instances:
      currencyExchangeService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      currencyExchangeService:
        registerHealthIndicator: true
        maxAttempts: 6
        waitDuration: 1s
currency-exchange-service:
  base-url: ${SPRING_EXCHANGE_SERVICE_URL:http://localhost:8081}
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  r2dbc:
    url: r2dbc:h2:mem:///dbtest
    username: sa
    password: 1234
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    root: INFO
    com.empresa.proyecto: DEBUG